strip/cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:item_id>/', cart_add, name='cart_add'),
    path('remove/<int:item_id>/', cart_remove, name='cart_remove'),
]

strip/strip/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('strip_test.urls', namespace='strip_test'))

]

strip/strip_test/urls.py
from django.urls import path

from .views import *

app_name = 'strip_test'
urlpatterns = [
    path('items/<int:item_id>/', ShowItem.as_view(), name='item'),
    path('items', ShowItems.as_view(), name='items'),
    path('buy/<int:item_id>/', buy_item, name='buy_item'),
    path('config/', stripe_config),
    path('order/', CreateOrder.as_view(), name='order'),
    path('order/<int:order_id>/', MyOrder.as_view(), name='orders'),
    path('order/<int:order_id>/buy/', buy_items, name='buy_items'),
    path('success/', SuccessView.as_view()),
    path('cancel/', CancelledView.as_view()),
]

strip/cart/models.py
from django.db import models

# Create your models here.

strip/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST

from .cart import Cart
from strip_test.models import Item


@require_POST  # метод POST
def cart_add(request, item_id):
    cart = Cart(request)
    product = get_object_or_404(Item, id=item_id)
    cart.add(product=product)

    return redirect('cart:cart_detail')


def cart_remove(request, item_id):
    cart = Cart(request)
    product = get_object_or_404(Item, id=item_id)
    cart.remove(product)

    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)

    return render(request, 'detail.html', {'cart': cart})

strip/cart/templates/detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  Корзина покупок
{% endblock %}

{% block content %}
  <h3 style="font-size: 100%; margin: 20px 0px 10px 70px; color: DarkGreen">Корзина покупок</h3>
  <table style="font-size: 100%; margin: 20px 20px 20px 70px; color: Black; border-spacing: 20px 40px;">
    <thead>
      <tr>
        <th style="padding: 10px">Товар</th>
        <th style="padding: 10px"> Удалить</th>
        <th style="padding: 10px">Кол-во</th>
        <th style="padding: 10px"> Цена за шт</th>
        <th style="padding: 10px">Общая стоимость</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart %}
        {% with product=item.product %}
          <tr>
            <td style="padding: 10px">{{ product.name }}</td>
            <td style="padding: 10px"><a href="{% url 'cart:cart_remove' product.id %}" style="color: MidnightBlue">Удалить</a></td>
            <td style="padding: 10px">{{ item.quantity }}</td>
            <td style="padding: 10px">USD {{ item.price }}</td>
            <td style="padding: 10px">USD {{ item.total_price }}</td>
          </tr>
        {% endwith %}
      {% endfor %}
      <tr>
        <td style="padding: 10px; color: DarkGreen">Всего</td>
        <td colspan="4" style="padding: 10px"></td>
        <td style="padding: 10px; color: DarkGreen">USD {{ cart.get_total_price }}</td>
      </tr>
    </tbody>
  </table>
  <form action="{% url 'strip_test:items' %}" method="get" id="form2">
      {% csrf_token %}
  </form>
  <form action="{% url 'strip_test:order' %}" method="get" id="form3">
      {% csrf_token %}
  </form>
  <section class="section">
      <div class="container" style="margin: 20px 0px 10px 30px;">
        <button class="button is-primary" id="toshop" type="submit" form="form2">В магазин</button>
        <button class="button is-primary" id="toorder" type="submit" form="form3">Оформить</button>
      </div>
  </section>
{% endblock %}