strip/cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:item_id>/', cart_add, name='cart_add'),
    path('remove/<int:item_id>/', cart_remove, name='cart_remove'),
]

strip/strip/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('strip_test.urls', namespace='strip_test'))

]

strip/strip_test/urls.py
from django.urls import path

from .views import *

app_name = 'strip_test'
urlpatterns = [
    path('items/<int:item_id>/', ShowItem.as_view(), name='item'),
    path('items', ShowItems.as_view(), name='items'),
    path('buy/<int:item_id>/', buy_item, name='buy_item'),
    path('config/', stripe_config),
    path('order/', CreateOrder.as_view(), name='order'),
    path('order/<int:order_id>/', MyOrder.as_view(), name='orders'),
    path('order/<int:order_id>/buy/', buy_items, name='buy_items'),
    path('success/', SuccessView.as_view()),
    path('cancel/', CancelledView.as_view()),
]

strip/strip_test/models.py
from django.core.validators import MaxValueValidator
from django.db import models
from django.urls import reverse

DISCOUNT_DURATION_CHOICES = (
    ("once", "once"),
    ("forever", "forever"),
    ("repeating", "repeating"),
)

CURRENCY_CHOICES = [
    ('eur', 'eur'),
    ('usd', 'usd'),
]


class Item(models.Model):
    name = models.CharField(max_length=50, unique=True, verbose_name='название')
    description = models.CharField(max_length=100, verbose_name='описание')
    price = models.IntegerField(verbose_name='цена')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        ordering = ['name']

    def get_absolute_url(self):
        return reverse('strip_test:item', kwargs={'item_id': self.pk})


class Discount(models.Model):
    name = models.CharField(max_length=20)
    duration = models.CharField(choices=DISCOUNT_DURATION_CHOICES, max_length=100)
    percent_off = models.IntegerField(validators=[MaxValueValidator(100)])

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Скидка'
        verbose_name_plural = 'Скидки'
        ordering = ['name']


class Order(models.Model):
    first_name = models.CharField(max_length=50, verbose_name='Имя')
    last_name = models.CharField(max_length=50, verbose_name='Фамилия')
    email = models.EmailField(verbose_name='E-mail')
    address = models.CharField(max_length=250, verbose_name='Адрес')
    city = models.CharField(max_length=100, verbose_name='Город')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Создан')
    discount = models.ForeignKey(Discount, related_name='orders', on_delete=models.CASCADE,
                                 verbose_name='Скидка', blank=True, null=True)
    currency = models.CharField(max_length=20, verbose_name="Оплата в валюте", choices=CURRENCY_CHOICES,
                                default='usd')

    class Meta:
        ordering = ['-created']
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def __str__(self):
        return 'Order {}'.format(self.pk)

    def get_absolute_url(self):
        return reverse('strip_test:orders', kwargs={'item_id': self.pk})


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE, verbose_name='Заказ')
    items = models.ForeignKey(Item, related_name='order_items',
                              on_delete=models.CASCADE, verbose_name='Товары')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Цена')
    quantity = models.PositiveIntegerField(default=1, verbose_name='Количество')

    class Meta:
        verbose_name = 'Товар в заказе'
        verbose_name_plural = 'Товары в заказе'

    def __str__(self):
        return '{}'.format(self.pk)

strip/strip_test/forms.py
from django import forms
from .models import Order


class OrderCreateForm(forms.ModelForm):

    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email', 'address', 'city', 'discount', 'currency']

    widgets = {
        'discount': forms.Select()
    }

strip/strip_test/views.py
from django.conf import settings
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import DetailView, ListView, CreateView, TemplateView
from .forms import OrderCreateForm
from .models import Item, OrderItem, Order
from cart.cart import Cart
from .utils import create_session


class ShowItem(DetailView):
    model = Item
    template_name = 'Item.html'
    context_object_name = 'item'
    pk_url_kwarg = "item_id"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f'Товар - {context["item"].name}'
        context['cart'] = Cart(self.request)
        return context


class ShowItems(ListView):
    model = Item
    template_name = 'Items.html'
    context_object_name = 'items'
    pk_url_kwarg = "item_id"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f'Товары'
        context['cart'] = Cart(self.request)
        return context


class CreateOrder(CreateView):
    template_name = 'create.html'
    form_class = OrderCreateForm

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f'Заказ'
        context['cart'] = Cart(self.request)
        return context

    def post(self, request, *args, **kwargs):
        cart = Cart(request)
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        if form.is_valid():
            order = form.save()
            for item in cart:
                OrderItem.objects.create(order=order,
                                         items=item['product'],
                                         price=item['price'],
                                         quantity=item['quantity'])
            cart.clear()
        return redirect('strip_test:orders', order_id=order.pk)


class MyOrder(DetailView):
    model = Order
    template_name = 'created.html'
    context_object_name = 'order'
    pk_url_kwarg = "order_id"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f'Заказ - {context["order"].pk}'
        return context


class SuccessView(TemplateView):
    template_name = 'success.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Мой магазин"
        return context


class CancelledView(TemplateView):
    template_name = 'cancel.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Мой магазин"
        return context


def buy_item(request, item_id):
    if request.method == 'GET':
        item = get_object_or_404(Item, id=item_id)
        try:
            session = create_session([item], None, None, 'usd')
            return JsonResponse({'sessionId': session['id']})
        except Exception as e:
            print(e)
            return JsonResponse({'error': str(e)})


def buy_items(request, order_id):
    if request.method == 'GET':
        items_in_order = OrderItem.objects.filter(order__id=order_id)
        order = Order.objects.get(pk=order_id)
        items = [i.items for i in items_in_order]
        try:
            session = create_session(items, order.email, order.discount, order.currency)
            return JsonResponse({'sessionId': session['id']})
        except Exception as e:
            print(e)
            return JsonResponse({'error': str(e)})


def stripe_config(request):
    if request.method == 'GET':
        stripe_config = {'publicKey': settings.STRIPE_PUBLIC_KEY}
        return JsonResponse(stripe_config, safe=False)

strip/strip_test/templates/Item.html
{% extends "base.html" %}
{% load static %}

{% block title %}
{{ title }}
{% endblock %}
{% block content %}
    <h1 style="font-size: 150%; font-weight:bold; margin: 20px 0px 10px 70px; color: DarkGreen">Товар</h1>
    <h3 style="font-size: 120%; font-weight:bold; margin: 20px 0px 10px 70px; color: DarkGreen">{{ item.name }}</h3>
    <p style="font-size: 120%; margin: 20px 0px 10px 70px; color: DarkGreen">{{ item.description }}</p>
    <p style="font-size: 120%; margin: 20px 0px 10px 70px; color: DarkGreen">{{ item.price }} USD</p>
    <form action="{% url 'cart:cart_add' item.pk %}" method="post" id="form1">
      {% csrf_token %}
    </form>
    <section class="section">
      <div class="container" style="margin: 20px 0px 10px 30px;">
        <button class="button is-primary" id="submitBtn">Купить</button>
        <button class="button is-primary" id="addToCart" type="submit" form="form1">Добавить в корзину</button>
      </div>
    </section>
    <script type="text/javascript">
        fetch("/config/")
        .then((result) => { return result.json(); })
            .then((data) => {
            var stripe = Stripe(data.publicKey);
            var pk = appConfig.pk;
            console.log(pk);
            console.log(data.publicKey);
            document.querySelector("#submitBtn").addEventListener("click", () => {
                fetch(`/buy/${pk}`)
                    .then((result) => { return result.json(); })
                    .then((data) => {
                        return stripe.redirectToCheckout({sessionId: data.sessionId})
                            .then((res) => {
                                console.log(res);
                            });
                    });
            });
        });
    </script>
{% endblock %}

strip/strip_test/templates/Items.html
{% extends "base.html" %}

{% block title %}
{{ title }}
{% endblock %}
{% block content %}
    <div style="font-size: 150%; font-weight:bold; margin: 20px 0px 10px 70px; color: DarkGreen">
        Товары
    </div>
    <br>
    {% for item in items %}
    <div>
        <a href="{{ item.get_absolute_url }}" style="font-size: 120%; font-weight:bold; margin: 20px 0px 10px 70px; color: MidnightBlue">{{ item.name }}</a>
        <p style="font-size: 100%; font-weight:bold; margin: 20px 0px 10px 70px; color: DarkGreen">USD {{ item.price }}
    </div>
    <br>
    {% endfor %}
{% endblock %}

strip/strip_test/templates/base.html
{% load static %}

<!DOCTYPE html>
    <html>
        <head>
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
            <script src="https://js.stripe.com/v3/"></script>
            <script type="text/javascript">
                window.appConfig = {
                pk: '{{ item.pk }}',
                order_pk: '{{ order.pk }}'
                }
            </script>
            <script defer src="https://use.fontawesome.com/releases/v5.15.4/js/all.js"></script>
            <meta charset="utf-8" />
            <title>
                {% block title %}
                Мой магазин
                {% endblock %}
            </title>
        </head>
        <body>
            <div id="header">
                <a href="{% url 'strip_test:items' %}" style="font-size: 120%; font-weight:bold;
                margin: 20px 0px 10px 70px; color: MidnightBlue">Мой магазин</a>
            </div>
            <div>
                <div style="font-size: 120%; font-weight:bold; margin: 20px 0px 10px 70px; color: DarkGreen">
                {% with total_items=cart|length %}
                    {% if cart|length > 0 %}
                        Ваша корзина:
                    <a href="{% url 'cart:cart_detail' %}" style="font-size: 80%; margin: 20px 0px 10px 70px; color: MidnightBlue">
                        {{ total_items }} шт, USD {{ cart.get_total_price }}
                    </a>
                    {% else %}
                    Ваша корзина пустая
                    {% endif %}
                {% endwith %}
                </div>
            </div>
            <div id="content">
                {% block content %}
                {% endblock %}
            </div>
        </body>
    </html>

strip/strip_test/templates/cancel.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.15.4/js/all.js"></script>
  </head>
  <body>
  <section class="section">
    <div class="container">
      <p style="font-size: 150%; font-weight:bold; margin: 20px 0px 10px 70px; color: DarkGreen">
        Оплата не прошла. Пожалуйста, повторите попытку позже!</p>
    </div>
  </section>
  </body>
</html>

strip/strip_test/templates/create.html
{% extends "base.html" %}

{% block title %}Оформление заказа{% endblock %}

{% block content %}
    <h1 style="font-size: 100%; margin: 20px 0px 10px 70px; color: DarkGreen">Оформление заказа</h1>
    <div class="order-info">
        <h3 style="font-size: 90%; margin: 20px 0px 10px 70px; color: DarkGreen">Ваш заказ</h3>
        <ul>
            {% for item in cart %}
                <li style="font-size: 100%; margin: 20px 0px 10px 70px; color: DarkGreen">
                    {{ item.quantity }}x {{ item.product.name }}
                    <span style="font-size: 100%; margin: 20px 0px 10px 70px; color: Black">USD {{ item.total_price }}</span>
                </li>
            {% endfor %}
        </ul>
        <p style="font-size: 100%; margin: 20px 0px 10px 70px; color: DarkGreen">Общая сумма: USD {{ cart.get_total_price }}</p>
    </div>
    <form action="." method="post" class="order-form" style="font-size: 100%; width: 200px; margin: 20px 0px 10px 70px; color: DarkGreen">
        {{ form.as_p }}
        <br>
        <p><input type="submit" value="Оформить заказ" class="button is-primary"></p>
        {% csrf_token %}
    </form>
{% endblock %}

strip/strip_test/templates/created.html
{% extends "base.html" %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <h1 style="font-size: 100%; margin: 20px 0px 10px 70px; color: DarkGreen">Спасибо!</h1>
    <p style="font-size: 100%; margin: 20px 0px 10px 70px; color: DarkGreen">Ваш заказ принят. Ваш номер заказа:
        <strong>{{ order.id }}</strong>.</p>
    <section class="section">
      <div class="container" style="margin: 20px 0px 10px 30px;">
        <button class="button is-primary" id="submitBtn_2">Оплатить</button>
      </div>
    </section>
    <script type="text/javascript">
        fetch("/config/")
        .then((result) => { return result.json(); })
            .then((data) => {
            var stripe = Stripe(data.publicKey);
            var pk = appConfig.order_pk;
            console.log(pk);
            console.log(data.publicKey);
            document.querySelector("#submitBtn_2").addEventListener("click", () => {
                fetch(`/order/${pk}/buy`)
                    .then((result) => { return result.json(); })
                    .then((data) => {
                        return stripe.redirectToCheckout({sessionId: data.sessionId})
                            .then((res) => {
                                console.log(res);
                            });
                    });
            });
        });
    </script>
{% endblock %}

strip/strip_test/templates/success.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.15.4/js/all.js"></script>
  </head>
  <body>
  <section class="section">
    <div class="container">
      <p style="font-size: 150%; font-weight:bold; margin: 20px 0px 10px 70px; color: DarkGreen">Спасибо! Ваша оплата прошла успешно</p>
    </div>
  </section>
  </body>
</html>